spring.application.name=online-grocery-system
server.port=8080

# Shows changes to HTML/CSS without restarting
spring.thymeleaf.cache=false

# Use our own error.html instead of Spring's default error page
server.error.whitelabel.enabled=false
